name: build

on:
  push:
    branches:    
      - master
jobs:
  build:
    strategy:
      matrix:
        pico_board: ["pico", "pico2"]
        pico_platform: ["rp2040", "rp2350", "rp2350-riscv"]
        exclude:
          - pico_board: "pico"
            pico_platform: "rp2350"
          - pico_board: "pico"
            pico_platform: "rp2350-riscv"
          - pico_board: "pico2"
            pico_platform: "rp2040"

    env:
      BUILD_TYPE: Release

    runs-on: ubuntu-latest

    steps:

    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib

    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Configure
      run: |
        git clone --branch 2.0.0 https://github.com/raspberrypi/pico-sdk.git external/pico-sdk
        cd external/pico-sdk
        git submodule update --init --recursive
        cd ../..
        git clone https://github.com/olikraus/u8g2.git external/u8g2
        cd external/u8g2
        git reset --hard e6a66ee0de9f863f898ddad5fe50a112d159de80

    - name: RiscV_compiler
      if: ${{ matrix.pico_platform == 'rp2350-riscv' }}
      run: |
        wget https://buildbot.embecosm.com/job/riscv32-gcc-centos7-release/19/artifact/riscv32-embecosm-centos7-gcc13.2.0.tar.gz
        tar -xzvf riscv32-embecosm-centos7-gcc13.2.0.tar.gz -C external
      
    - name: Build
      run: |
        export PICO_TOOLCHAIN_PATH=$PWD/external/riscv32-embecosm-centos7-gcc13.2.0
        export PICO_SDK_PATH=../external/pico-sdk
        mkdir -p build
        cd build
        cmake -DPICO_PLATFORM=${{ matrix.pico_platform }} -DPICO_BOARD=${{ matrix.pico_board }} -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make -j

    - uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a
      with:
        name: binaries-${{ matrix.pico_platform }}-${{ matrix.pico_board }}
        path: |
          build/*.uf2

